version: '3'
services:
  rabbitmq:
    image: 'rabbitmq_stomp:1.0.0'
    container_name: rabbitmq_stomp
# restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
      - "15674:15674"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
